spring.session.store-type=jdbc

spring.session.jdbc.table-name=SPRING_SESSION

spring.session.jdbc.initialize-schema=always

spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-mysql.sql

spring.config.import=file:.env[.properties]

spring.application.name=espaco_verde

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USER}

spring.datasource.password=${DB_PASSWORD}
