spring.session.store-type=jdbc

spring.session.jdbc.table-name=SPRING_SESSION

spring.session.jdbc.initialize-schema=always

spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-mysql.sql

spring.application.name=espaco_verde

spring.jpa.show-sql = true

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USER}

spring.datasource.password=${DB_PASSWORD}

wa.api.url=${API_URL}

wa.api.acess.token=${ACESS_TOKEN}

wa.api.phone.number.id=${PHONE_NUMBER_ID}

wa.api.verify.token=${VERIFY_TOKEN}

local.api.url=${LOCAL_API_URL}

dir.uploads = ./uploads